### ISSUE TITLE
Complete log not accessible in ssh dir

### ISSUE THREAD

**Issue by ewilly** [YunoHost/CI_package_check#23]
When using  https://ci-apps-dev.yunohost.org to test a package, a complete log have to be duplicated and accessible unfortunately it's not.
For example :
`The complete log for this application was duplicated and is accessible at https://ci-apps-dev.yunohost.org/jenkins/logs/_home_yunohost.app_ssh_chroot_directories_ewilly_data_homeassistant_ynh_complete.log`
should be 
`https://ci-apps-dev.yunohost.org/jenkins/logs/_home_yunohost.app/ssh_chroot_directories/ewilly/data/homeassistant_ynh_complete.log`

This is due to line 512 in https://github.com/YunoHost/CI_package_check/blob/master/pcheckCI.sh
```
	# From the repositery, remove http(s):// and replace all / by _ to build the log name
	app_log=${log_dir}$(echo "${repo#http*://}" | sed 's@[/ ]@_@g')$architecture.log
	# The complete log is the same of the previous log, with complete at the end.
	complete_app_log=${log_dir}$(basename --suffix=.log "$app_log")_complete.log
```

**Comment by yalh76** [comment]
logs can be found at https://ci-apps-dev.yunohost.org/ci/logs/
