### ISSUE TITLE
Translate README ;)

### ISSUE THREAD

**Issue by jedie** [YunoHost/CI_package_check#27]
Please can somebody translate the README in english?

My questions was: What's the difference between https://github.com/YunoHost/package_check and https://github.com/YunoHost/CI_package_check ?!?

**Comment by maniackcrudelis** [comment]
Hi @jedie, sorry I did not translate that part while I was working on it.

To make it simple, CI_package_check is a tool that uses package_check itself. That's a bunch of scripts to deploy a CI using package_check to test the apps.
It either uses Jenkins or Yunorunner (built for that purpose) as a GUI for the CI and provides an interface between the GUI and package_check itself.

That's mostly for YunoHost team purpose (as far as I know) to run the different CI. But I think you can find some posts on the forum explaining how to deploy it on your own if you need to.

Usually if you need to test your own apps, using package_check only is enough.

FYI: Actually the readme doesn't really explain what is it... It wouldn't have helped you.

**Comment by alexAubin** [comment]
I reworked the README (now in english), so should be done :+1:
