### ISSUE TITLE
Tartiflette not abble to retrieve levels

### ISSUE THREAD

**Issue by yalh76** [YunoHost/CI_package_check#33]
It seems that since CI_package_check has been upgraded, tartiflette is no more able to retrieve levels =>
[https://ci-apps-unstable.yunohost.org/ci/logs/list_level_testing.json](https://ci-apps-unstable.yunohost.org/ci/logs/list_level_testing.json) no more exists ...

https://github.com/YunoHost/tartiflette/blob/ee508edf55ad8cc8adf8a5b9738ba5fb980f9182/app/models/appci.py#L22-L48

As consequence:
![image](https://user-images.githubusercontent.com/30271971/110257676-44755580-7f9f-11eb-965e-0707c2f5148a.png)

**Comment by alexAubin** [comment]
Fixed in https://github.com/YunoHost/tartiflette/commit/a29211ef080fb29f767b8cf57912ed1cb28df92d and next commits
